### ISSUE TITLE
Error: Each row of output must be identified by a unique combination of keys.

### ISSUE THREAD

**Issue by jfoster-f** [Olink-Proteomics/OlinkRPackage#10]
When running the examples I get the following error when running this code:

Code:
bridge_samples <- intersect(x = npx_data1$SampleID,
               y = npx_data2$SampleID)

bridge_normalized_data <- olink_normalization(df1 = npx_data1,
                        df2 = npx_data2,
                        overlapping_samples_df1 = bridge_samples,
                        df1_project_nr = "20200001",
                        df2_project_nr = "20200002",
                        reference_project = "20200001")

Error:
Bridging normalization with overlapping samples will be performed.
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 8832 rows:
* 3681, 3695
* 3701, 3715
* 16561, 16575
* 16581, 16595
* 16601, 16615
* 16621, 16635...

**Comment by klevdiamanti** [comment]
Hi there.
I suspect you do not have the latest vignette version, where this issue is resolved. You get an error because the "Project" column for the control samples from the example data frames is _NA_. You can either resolve this by updating OlinkAnalyze or by doing the following to your existing code:
```
bridge_samples <- intersect(x = npx_data1$SampleID, y = npx_data2$SampleID)
bridge_samples <- bridge_samples[!grepl("^CONTROL_", bridge_samples)]

bridge_normalized_data <- olink_normalization(df1 = npx_data1, df2 = npx_data2, overlapping_samples_df1 = bridge_samples, df1_project_nr = "20200001", df2_project_nr = "20200002", reference_project = "20200001")
```
Please do update to the latest version of OlinkAnalyze.
