### ISSUE TITLE
integration of multiple data sets

### ISSUE THREAD

**Issue by shaka87** [Olink-Proteomics/OlinkRPackage#12]
Hello, 

I have an Olink dataset that was acquired across multiple plates, however olink_normalization() only normalizes 2 datasets. 
What strategy do you recommend for normalization of >2 datasets? 

Thank you!

livius

**Comment by EmmettSprecher-Olink** [comment]
Hi Livius!

Depending on how your data was run, you may not have to do normalization.  If your data is from a multi-plate project (a project with more than 88 samples, thereby requiring the samples to be split across multiple plates), and if your samples were randomized across the multiple plates, then your plates of data were likely already combined by the Olink lab using intensity normalization.  You should be able to figure this out by asking whoever sent the samples to Olink whether the samples were randomized.  Also it should be mentioned in the Certificate of Analysis that came with the data.

If you do in fact need to normalize more than 2 datasets (or more than 2 plates of data), then you can do it by using the `olink_normalization()` function iteratively.  For example if there are the same 16 bridge samples in each datasets 1, 2, 3, 4, etc, then you would write something approximately like:


`bridged_data <- olink_normalization(df1 = npx_df1, df2 = npx_df2, .....)` 
`bridged_data <- olink_normalization(df1 = bridged_data, df2 = npx_df3, .....)`
`bridged_data <- olink_normalization(df1 = bridged_data, df2 = npx_df4, .....)`
_etc._


However, this process currently has some tricky elements because you need to specify the bridge samples carefully.  This is because if you have the same bridge samples in each of the projects, their combined data will have multiple samples with the same name, which can cause problems in later operations.  Also, if you want to keep the adjustment factors separate from each bridging step, you will have to rename that column between successive bridging iterations.

Hope that helps!

Emmett

**Comment by shaka87** [comment]
Dear Emmett, 

that makes a lot of sense! 

Thank you very much, 

livius
