### ISSUE TITLE
Solid tissue vs plasma based Olink data

### ISSUE THREAD

**Issue by Shicheng-Guo** [Olink-Proteomics/OlinkRPackage#126]
Dear Team, 

I am wondering is there any difference from the computational analysis side for Solid tissue vs plasma based Olink data? I think the analytic method should be same, but just want to have a double checking. 

Thanks

Shicheng

**Comment by kathy-nevola** [comment]
Hi Shicheng,

Great question and thanks for reaching out. In terms of analytical methods, for Olink NPX data, the analytical method is the same regardless of sample type. Since Target 48 is in absolute quantification, it does not necessarily follow normal distribution so it is recommended to check this assumption and either log transform the data or use non-parametric tests. 

Depending on the tissue type and scientific questions, it is always important to perform additional QC checks to make sure the assumptions are valid. There are functions within Olink Analyze for PCA, NPX distribution, and Sample IQR vs Sample Median NPX, which can be used to determine outliers or trends within your data. 


One to look out for is if one subgroup of your study has a higher median NPX than another subgroup, due to a higher overall protein concentration. It is still fine in this case to do the analysis as you usually would but knowing that the overall protein concentration may be driving your results. If you wanted to know what proteins were different regardless of overall protein concentration, you could either account for protein concentration in your model or you could median adjust the dataset.

For example, here I've created an extreme example where the treated group has higher NPX than the untreated group:
![image](https://user-images.githubusercontent.com/72228735/163817763-9edeb480-34c7-4bf3-9600-07548fb41bab.png)

If you were to perform a t-test on this data you would end up with something like this where the results look very skewed:
![image](https://user-images.githubusercontent.com/72228735/163818089-42ee9c4b-2e09-417b-91aa-d4964e7c2f72.png)

In this case, median centering can adjust for differences in protein concentration between groups if this is something you are interested in adjusting for in your data analysis. It's not required in all cases but it can be useful if protein concentration differences are interfering with your statistical analysis.

I hope this helps. 

Thanks,
Kathy

**Comment by kathy-nevola** [comment]
If you have any other questions, feel free to email support@olink.com or biostat@olink.com who may be able to provide more information specific to your project.
