### ISSUE TITLE
Non-intuitive interface for Friedman tests

### ISSUE THREAD

**Issue by khkk378** [Olink-Proteomics/OlinkRPackage#161]
This might just be me, but I find it unintuitive what ends up as blocks in the current implementation of Friedman tests. In several other of the stats functions you specify this yourself (e.g. subject). Could this use the same implementation?

**Comment by kathy-nevola** [comment]
Hi @khkk378,

Thanks for your suggestion. Can you provide some additional information about the implementation you would like to see? We will look into your suggested enhancement.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example, I want to be able to visualize and summarize the results of my t-test analysis. If there are particular packages or external functions you would like integration with, please list those here.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please include where in your analysis workflow this solution would take place, any suggestions for inputs, and what you would want to see as the output. For example: I would like to see a volcano plot, where I would input the t-test results and the significant proteins would be highlighted and/or labeled. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. 

**Additional context**
Add any other context or screenshots about the feature request here.
