### ISSUE TITLE
Bug in visualize pathway enrichment

### ISSUE THREAD

**Issue by khkk378** [Olink-Proteomics/OlinkRPackage#162]
This ends up visualizing the least significant gene sets.

https://github.com/Olink-Proteomics/OlinkRPackage/blob/8f13defa38557bdb0cffca688ade490ade6732d6/OlinkAnalyze/R/olink_Pathway_Visualization.R#L44

**Comment by kathy-nevola** [comment]
Hi @khkk378, 

Thank you for sharing your finding. We will look into this issue. Can you please give additional information regarding this bug?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System Information:**
 - OS: [e.g. Mac, Windows, Linux]
 - R Version
 - Package Information: (or paste sessionInfo() here)

**Additional context**
Add any other context about the problem here.

In the example code:
```library(dplyr)
npx_df <- npx_data1 %>% filter(!grepl('control',SampleID, ignore.case = TRUE))
ttest_results <- olink_ttest(df=npx_df,
                             variable = 'Treatment',
                             alternative = 'two.sided')

  gsea_results <- olink_pathway_enrichment(data = npx_data1, test_results = ttest_results)
  ora_results <- olink_pathway_enrichment(data = npx_data1,
                                          test_results = ttest_results, method = "ORA")
  olink_pathway_visualization(enrich_results = gsea_results)
```
The pathway with the lowest p-value is LEE_BMP2_TARGETS_UP, which appears at the top of the figure: 
![image](https://user-images.githubusercontent.com/72228735/175646568-6493cc65-dfc6-4a34-a063-9165a4d1d648.png).

**Comment by khkk378** [comment]
Hi Kathy,

The code takes the results, sorts by descending p-value (so the worst ones first) and then takes the top `number_of_terms`. So it's not a matter of the visualization, it's about which terms end up being visualized.

Cheers,
Rasmus
