### ISSUE TITLE
Error in filter(., Panel == "Olink CARDIOMETABOLIC") :    object 'Panel' not found

### ISSUE THREAD

**Issue by alisahinmd** [Olink-Proteomics/OlinkRPackage#203]
Hi, im new one for Olink 

Error in filter(., Panel == "Olink CARDIOMETABOLIC") : 
  object 'Panel' not found 
i take this error
how can i fix it ?

thanks.

**Comment by klevdiamanti** [comment]
Hi,

I am note sure this has to do with Olink or the Olink Analyze R library, and I do not think that this is the correct forum for this question as it looks like a basic R question.

The error you receive is most likely because you are using the native R function 'filter' instead of the dplyr function 'filter'. To fix it please import the dplyr library and the code below should work:
```
library(OlinkAnalyze)
library(dplyr)

npx_data1 %>%
  filter(.data = ., Panel == "Olink Cardiometabolic")
```

Best,
Klev

**Comment by kathy-nevola** [comment]
If you continue to have issues, please email biostattools@olink.com or create a new issue including the code that lead to this error.
Thanks,
Kathy
