### ISSUE TITLE
olink using Enrichment is gene database 

### ISSUE THREAD

**Issue by wdb-web** [Olink-Proteomics/OlinkRPackage#209]
The msigdb::msigdb of the select_db function uses the gene database, and olink makes proteins, can the gene database be used?

**Comment by wdb-web** [comment]
.get_kegg_org<- function(org=org) {
     name_rmends <- function(.x) {
      .x %>%str_locate_all(" - ")%>%.[[1]]->jk
      jk[nrow(jk),]%>%.[1]%>%{.-1}%>%str_sub(.x, end =.)%>%return
    }# getname
    x<-readLines("https://www.genome.jp/kegg-bin/download_htext?htext=br08901.keg&format=htext&filedir=")
    x%>%str_detect("!" )%>%which()->s
    x[(s[1]+1):(s[2]-1)]%>%str_replace("<b>","  ")%>%str_remove("</b>")->a
    x[(s[1]+1):(s[2]-1)]%>%str_replace("<b>","  ")%>%str_remove("</b>")%>%as.data.frame()->das
    das$A<-NA
    das$B<-NA
    das$C<-NA
    a[str_detect(a,"^A")%>%which()]%>%str_remove("A  ")->das$A[str_detect(a,"^A")%>%which()]
    a[str_detect(a,"^B")%>%which()]%>%str_remove("B  ")->das$B[str_detect(a,"^B")%>%which()]
    a[str_detect(a,"^C")%>%which()]%>%str_remove("C  ")%>%str_remove("  [0-9][0-9][0-9][0-9][0-9]  ")->das$C[str_detect(a,"^C")%>%which()]
    das %>%
      fill(A, .direction = "up") %>%
      fill(B, .direction = "up") %>%na.omit()->s
  x1<-fread("http://rest.kegg.jp/list/pathway",head=F)
  x2<-fread(paste("http://rest.kegg.jp/list/pathway/",org,sep=""),head=F)

  x2$V2%>%purrr::map(~name_rmends(.x))%>%unlist()%>%cbind(x2[,1])%>% setNames(c("V2","name"))  ->pathways# getname
                       
   y<-fread(paste("http://rest.kegg.jp/link/",org,"/pathway",sep=""),head=F)%>%setNames(c("name","V2"))
   x<-fread(paste("http://rest.kegg.jp/conv/",org,"/uniprot",sep=""),head=F)
   par=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( full_join(x,y,by="V2")%>%na.omit,by="name")%>%
   .[,c(2,1,4)]%>%setNames(c("ID","name","Protacxns_id"))%>% dplyr::group_by(ID ,name )%>% 
   dplyr::summarise(Protacxns_id=Protacxns_id%>% str_remove("^up:")%>% paste( sep = "|", collapse = "|" )  )%>%
   ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%inner_join(s[,c(2,4)],by=c("name"="C"))%>%
   dplyr::summarise( ID = ID,name=name,group=A,org="KEGG",Protacxns_id=Protacxns_id) 

   gene=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( y,by="name")%>%
   .[,c(2,1,4)]%>%setNames(c("ID","name","Gene_id"))%>% dplyr::group_by(ID ,name )%>% 
   dplyr::summarise(Gene_id=Gene_id%>% str_remove(.,"^(.+?)\\:") %>% paste( sep = "|", collapse = "|" ))%>%
   ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%inner_join(s[,c(2,4)],by=c("name"="C"))%>%
   dplyr::summarise( ID = ID,name=name,group=A,org="KEGG",Gene_id=Gene_id) 



  fuu<-full_join(par,gene,by = c("ID", "name", "group", "org"))%>%
    dplyr::mutate(name, group,org,Gene_id,  Protacxns_id)

  return(fuu)
  }

**Comment by wdb-web** [comment]
WikiPathways database of
Hijack of ubiquitination by SARS-CoV-2 pathway, only genes, no proteins, I can use gene and protein databases to do it, the results are different

**Comment by kathy-nevola** [comment]
Hi! Thanks for your question about Olink Analyze pathway enrichment. 

 When looking at databases for pathway enrichment, our aim was to support the most common databases used for pathway enrichment. These databases detail the functional, molecular, and biological annotations that these proteins are involved in. MSigDB is a resource of tens of thousands of annotated gene sets. These gene sets are made up of the genes that encode the proteins that act in the biological processes. Therefore Olink's technology measures the functional unit (the protein concentration) and enrichment can be performed on statistical analysis results that are run on these measures. 

I am also adding this image from this paper (https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-15-S9-S1/figures/1) that also mentions that proteomics data can be mapped to MsigDB genesets, which illustrates the mapping process very well. 

WikiPathways is a database of biological pathways which is maintained by the scientific community. WikiPathways is included as a subset of the msigdb database as shown here: https://www.gsea-msigdb.org/gsea/msigdb/human/collections.jsp#C2. 

Depending on the method of enrichment, the database used, and the statistical results provided, the results may be different. Can you provide me with an example of the code you used and the expected results so that I can help? At this point, I do not believe that this is a result of a bug in our code so I will remove this tag for now.

Thanks,
Kathy

**Comment by wdb-web** [comment]
.get_kegg_org<- function(org=org) {
     name_rmends <- function(.x) {
      .x %>%str_locate_all(" - ")%>%.[[1]]->jk
      jk[nrow(jk),]%>%.[1]%>%{.-1}%>%str_sub(.x, end =.)%>%return
    }# getname
    x<-readLines("https://www.genome.jp/kegg-bin/download_htext?htext=br08901.keg&format=htext&filedir=")
    x%>%str_detect("!" )%>%which()->s
    x[(s[1]+1):(s[2]-1)]%>%str_replace("<b>","  ")%>%str_remove("</b>")->a
    x[(s[1]+1):(s[2]-1)]%>%str_replace("<b>","  ")%>%str_remove("</b>")%>%as.data.frame()->das
    das$A<-NA
    das$B<-NA
    das$C<-NA
    a[str_detect(a,"^A")%>%which()]%>%str_remove("A  ")->das$A[str_detect(a,"^A")%>%which()]
    a[str_detect(a,"^B")%>%which()]%>%str_remove("B  ")->das$B[str_detect(a,"^B")%>%which()]
    a[str_detect(a,"^C")%>%which()]%>%str_remove("C  ")%>%str_remove("  [0-9][0-9][0-9][0-9][0-9]  ")->das$C[str_detect(a,"^C")%>%which()]
    das %>%
      fill(A, .direction = "up") %>%
      fill(B, .direction = "up") %>%na.omit()->s
  x1<-fread("http://rest.kegg.jp/list/pathway",head=F)
  x2<-fread(paste("http://rest.kegg.jp/list/pathway/",org,sep=""),head=F)

  x2$V2%>%purrr::map(~name_rmends(.x))%>%unlist()%>%cbind(x2[,1])%>% setNames(c("V2","name"))  ->pathways# getname
                       
   y<-fread(paste("http://rest.kegg.jp/link/",org,"/pathway",sep=""),head=F)%>%setNames(c("name","V2"))
   x<-fread(paste("http://rest.kegg.jp/conv/",org,"/uniprot",sep=""),head=F)
   par=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( full_join(x,y,by="V2")%>%na.omit,by="name")%>%
   .[,c(2,1,4)]%>%setNames(c("ID","name","Protacxns_id"))%>% dplyr::group_by(ID ,name )%>% 
   dplyr::summarise(Protacxns_id=Protacxns_id%>% str_remove("^up:")%>% paste( sep = "|", collapse = "|" )  )%>%
   ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%inner_join(s[,c(2,4)],by=c("name"="C"))%>%
   dplyr::summarise( ID = ID,name=name,group=A,org="KEGG",Protacxns_id=Protacxns_id) 

   gene=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( y,by="name")%>%
   .[,c(2,1,4)]%>%setNames(c("ID","name","Gene_id"))%>% dplyr::group_by(ID ,name )%>% 
   dplyr::summarise(Gene_id=Gene_id%>% str_remove(.,"^(.+?)\\:") %>% paste( sep = "|", collapse = "|" ))%>%
   ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%inner_join(s[,c(2,4)],by=c("name"="C"))%>%
   dplyr::summarise( ID = ID,name=name,group=A,org="KEGG",Gene_id=Gene_id) 



  fuu<-full_join(par,gene,by = c("ID", "name", "group", "org"))%>%
    dplyr::mutate(name, group,org,Protacxns_id,Gene_id)
  fuu[is.na(fuu)]<-"NULL"

  return(fuu)
  }

**Comment by wdb-web** [comment]
Many databases such as kegg separate the protein from the gene set. If the protein data is directly mapped to the gene, will there be false positives, that is, there is a gene in the pathway, but there is no protein?

**Comment by wdb-web** [comment]
I am not talking about the enrichment method, but I think there is still some gap between the gene set and the protein set on the same pathway

**Comment by wdb-web** [comment]
It's not a question of enrichment method, it's because there is still some gap between the gene set and the protein set on the same pathway

**Comment by kathy-nevola** [comment]
Hi @wdb-web  Can you should me an example of one of the differences you are seeing?  I'm having trouble locating the protein sets that you are referring to in KEGG.

**Comment by wdb-web** [comment]
library(tidyverse)
.get_kegg_org<- function(org=org) {
  name_rmends <- function(.x) {
    .x %>%str_locate_all(" - ")%>%.[[1]]->jk
    jk[nrow(jk),]%>%.[1]%>%{.-1}%>%str_sub(.x, end =.)%>%return
  }# getname
  x1<-data.table::fread("http://rest.kegg.jp/list/pathway",head=F)
  x2<-data.table::fread(paste("http://rest.kegg.jp/list/pathway/",org,sep=""),head=F)
  
  x2$V2%>%purrr::map(~name_rmends(.x))%>%unlist()%>%cbind(x2[,1])%>% setNames(c("V2","name"))  ->pathways# getname
  
  y<-data.table::fread(paste("http://rest.kegg.jp/link/",org,"/pathway",sep=""),head=F)%>%setNames(c("name","V2"))
  x<-data.table::fread(paste("http://rest.kegg.jp/conv/",org,"/uniprot",sep=""),head=F)
  par=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( full_join(x,y,by="V2")%>%na.omit,by="name")%>%
    .[,c(2,1,4)]%>%setNames(c("ID","name","Protacxns_id"))%>% dplyr::group_by(ID ,name )%>% 
    dplyr::summarise(Protacxns_id=Protacxns_id%>% str_remove("^up:")%>% paste( sep = "|", collapse = "|" )  )%>%
    ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%
    dplyr::summarise( ID = ID,name=name,org="KEGG",Protacxns_id=Protacxns_id) 
  
  gene=full_join(pathways,x1,by="V2")%>%na.omit%>%full_join( y,by="name")%>%
    .[,c(2,1,4)]%>%setNames(c("ID","name","Gene_id"))%>% dplyr::group_by(ID ,name )%>% 
    dplyr::summarise(Gene_id=Gene_id%>% str_remove(.,"^(.+?)\\:") %>% paste( sep = "|", collapse = "|" ))%>%
    ungroup%>% dplyr::mutate(ID= ID %>% str_remove("^path:") )%>%
    dplyr::summarise( ID = ID,name=name,org="KEGG",Gene_id=Gene_id) 
  fuu<-full_join(par,gene,by = c("ID", "name", "org"))
  fuu[is.na(fuu)]<-"NULL"
  
  return(fuu)
}
f=.get_kegg_org(org="hsa")

**Comment by wdb-web** [comment]
hsa00232 | Caffeine metabolism | P11245\|A4Z6T7\|P05177\|P11509\|P20853\|P47989\|P18440 | 10\|1544\|1548\|1549\|7498\|9

**Comment by wdb-web** [comment]
In this pathway, there are 7 proteins and 6 genes, because of the mathematical model of the ORA method, the enriched P values ​​are different

**Comment by wdb-web** [comment]
There are many more pathways like this

**Comment by kathy-nevola** [comment]
Hi @wdb-web,
Thanks for providing the example. This discrepancy between gene numbers and UniProtIDs is due to annotations in KEGG including UniProtIDs that are inferred from homology/unreviewed. Both P11245 and A4Z6T7 refer to the NAT2 protein. However, A4Z6T7 is an unreviewed UniProtID with an annotation score of 2/5 (https://www.uniprot.org/uniprotkb/A4Z6T7/entry) while P11245 is a reviewed UniProtID with an annotation score of 5/5 (https://www.uniprot.org/uniprotkb/P11245/entry).

This instance will not affect pathway enrichment with Olink for a few reasons:

1.  Each gene symbol will only map to one gene, which is why we chose to use gene symbols directly, rather than map gene symbols to UniProtIDs or EntrezIDs which can result in a many:many mapping.
2. When using ORA, a background list should also be uploaded which should only have 1 record per protein. Therefore the multiple records will not be double-counted in the statistical model. 


That being said, this is more of a general question about mapping between genes and proteins than a specific Olink Analyze question and therefore might be better suited for a meeting or discussion than a written conversation to choose the best method for your specific research question. I recommend reaching out to either our Olink Data Science team (biostat at olink.com) or our Olink Support team (support at olink.com). For general Olink information, please reach out to info at olink.com.
