### ISSUE TITLE
[BUG] Bridge normalization with >2 projects when bridge sample is shared

### ISSUE THREAD

**Issue by spkdog** [Olink-Proteomics/OlinkRPackage#239]
Hi,

I'm trying to bridge normalize from Target 96. I have 3 npx_data tibbles, with 8 bridge samples between each project, but one bridge sample is shared between the bridge samples of npx_data1 to npx_data2 and npx_data2 to npx_data3. These 3 projects were run at different times, thus I need to bridge normalize between them.

Bridge normalization of npx_data1 and npx_data2 works normally, but when trying to normalize the result from the normalization of npx_data1 and npx_data2 (let's call it npx_data_norm) to npx_data3, it yields with the tidyr::spread() error "! Each row of output must be identified by a unique combination of keys. Keys are shared for 184 rows" 

I suppose this is due to one bridge sample being shared between the two normalizations. Any solutions how to solve this problem? I checked the previous issues related to this problem, but they didn't provide an answer. Also updated the package.

```
overlap_samples <- intersect(npx_data_norm$SampleID, npx_data3$SampleID) %>% 
  data.frame() %>% 
  filter(!str_detect(., 'CONTROL_SAMPLE')) %>% #Remove control samples
  pull(.)

npx_data_norm <- olink_normalization(df1 = npx_data_norm, 
                                     df2 = npx_data3, 
                                     overlapping_samples_df1 = overlap_samples)
```

**System Information:**
 - OS: Windows
 - R Version: 4.2.2
 - Package Information: OlinkAnalyze_3.3.1

**Comment by kathy-nevola** [comment]
Hi @spkdog,

This issue is due to duplicate sample IDs, in this case caused by 2 sets of the bridging samples. To fix this issue, filter the reference project from npx_data_norm and use this as the input to olink_normalization. 

`
overlap_sample_1 <- intersect(npx_data1$SampleID, npx_data2$SampleID)  %>% 
  data.frame() %>% 
  filter(!str_detect(., 'CONTROL_SAMPLE')) %>% #Remove control samples
  pull(.)

overlap_sample_2 <- intersect(npx_data2$SampleID, npx_data3$SampleID) %>% 
  data.frame() %>% 
  filter(!str_detect(., 'CONTROL_SAMPLE')) %>% #Remove control samples
  pull(.)

# Bridge batch 2 to batch 1
npx_data_norm1 <- olink_normalization(df1 = npx_data1, 
                                     df2 = npx_data2, 
                                     overlapping_samples_df1 = overlap_samples_1)

# Filter for batch 2
npx_data2_norm <- npx_data_norm1  %>% 
 filter(Project = "P2")

# Bridge Batch 3 to batch 2
npx_data_norm2 <-  olink_normalization(df1 = npx_data2_norm, 
                                     df2 = npx_data3, 
                                     overlapping_samples_df1 = overlap_samples_2)

`
Let me know if there are any other issues.
Thanks,
Kathy
