### ISSUE TITLE
Covariate inclusion issue- reg

### ISSUE THREAD

**Issue by Manonanthini** [Olink-Proteomics/OlinkRPackage#32]
Hi,
 I have adjusted my normalized expression data for the covariates age and BMI . My aim is to find singificant proteins in a group.
I have used the following commands to get a list of significant Olink proteins specific to a particular group and selected protein for analysis If the protein is significantly dominant in a group in multiple pairwise comparisons(group1: group2,group2:group3 -infered as dominant in group 2)  

anova_results_adj <- olink_anova(df = df3, variable ="group_list", covariates = "AGE:BMI")
significant_assays_adj <- anova_results_adj%>% filter(Threshold == 'Significant') %>%  pull(OlinkID)
anova_posthoc_results_adj=olink_anova_posthoc(df3,variable = "group_list", effect = 'Cluster_name', covariates = "AGE:BMI").

My questions are 
1. Do I need to specify covariates in olink_anova_posthoc() also if do olink_anova with covariates and used the list of significant assays from anova?
2.  How  can I change 'sidak' to 'tukey' test or 'tukey' to 'sidak' for multiple pairwise comparisons?
3. Are the above-mentioned lines of commands could answer my questions?
4. Do I need to run Normalization following the command <- npx %>% select(OlinkID) %>%  distinct() %>%  mutate(Reference_NPX = 1) if I use data from different Olink Panels?
Thanks for the package. Please reply as the package was very useful and couldn't find a similar tool for the analysis.

Kind regards
Mano

**Comment by marisand** [comment]
Hi Mano,
Thanks for contacting us!
1. You need to put the same model in the first anova call as in the posthoc call, we are now making some documentation changes to make this clearer. I recommend running the two functions with the setting verbose = T to get a better overview of the computations that are performed under the hood. 
2. This is not possible at the moment. In our package we use a Tukey adjustment and the warning that displays comes from a package we are calling for the comparisons. We are looking into the warning, so keep an eye out for package updates. 
3. + 4. For these two questions I recommend that you contact us on biostat[at]olink.com so that we can discuss your setup and normalization needs in more detail. 
Kind regards,
Marianne
