### ISSUE TITLE
Working on All cases data: t-test 

### ISSUE THREAD

**Issue by karpat90** [Olink-Proteomics/OlinkRPackage#333]
Hello!

Thank you for a great package. Our OLINK dataset contains data for 100 patients, we don't have controls.
For example, I tried to test whether protein levels differ between sexes:
 anova_results_oneway <- olink_ttest(df = biomarker_data2, 
+                                     variable = "Sex")
0 assay(s) exhibited assay QC warning. For more information see the Assay_Warning column.
Error in olink_ttest(df = biomarker_data2, variable = "Sex") : 
  No assays passing the initial check. T-test will not be performed.

anova_results_oneway <- olink_wilcox(df = biomarker_data2, 
+                                     variable = "Sex")
0 assay(s) exhibited assay QC warning. For more information see the Assay_Warning column.
Mann-Whitney U Test is performed on F - M.
Error in wilcox.test.formula(NPX ~ Sex, data = ., conf.int = TRUE, ...) : 
  grouping factor must have exactly 2 levels
> table( biomarker_data2$Sex)

F     M 
62238 12259 

Could you help me with this?

Thank you

**Comment by kathy-nevola** [comment]
Hi @karpat90. Thanks for using Olink Analyze. I am sorry you are having issues with the t-test and wilcox functions. 

I wanted to get a bit more information on your dataset and analysis to better assist you. If you would prefer to provide this information via email, feel free to send an email to biostattools@olink.com and reference this issue in your email. 

- What Olink product is your dataset from? (Explore HT, Explore 384, Target 96, or Target 48)
- Was any data wrangling done upstream of this analysis? (ex: filtering out samples or assays, merging datasets, bridging, or otherwise altering the dataset) If so can you describe these changes and/or provide the code which generated these changes?
- Was the input data provided by Olink NPX Software (ex: NPX Signature, NPX Explore)
- Are there any additional warnings or messages that appear in the pipeline?

The error message from olink_ttest suggest that there are assays with NAs within the dataset which are being filtered out in the function.

The error message from olink_wilcok suggest that there is at least 1 assay where all of the subjects from 1 group have NA data. 

Can you try the following code and tell me what you get?

` table(biomarker_data2$Sex, useNA = "always")`

and 

```
biomarker_data2 |>
     dplyr::filter(!is.na(NPX)) |>
     dplyr::group_by(Assay, Sex) |>
     dplyr::summarise(n = dplyr::n()) |>
     tidyr::pivot_wider(names_from = Sex, values_from = n) |>
    dplyr::filter(F <= 1 | M <=1 | NA != 0)
```

**Comment by karpat90** [comment]
Hello!

Thank you for a prompt response ! Unfortunately, I don't have information about how data was pre-processed beyond standard cleaning. I inherited this data. I have requested the data you need and awaiting response:


I checked the data using your suggested commands:


table(biomarker_data2$Sex, useNA = "always")
 F     M  <NA> 
62258 12260     0 


biomarker_data2 |>
 dplyr::filter(!is.na(NPX)) |>
 dplyr::group_by(Assay, Sex) |>
 dplyr::summarise(n = dplyr::n()) |>
 tidyr::pivot_wider(names_from = Sex, values_from = n) |>
 dplyr::filter(F <= 1 | M <=1 | NA != 0)
`summarise()` has grouped output by 'Assay'. You can override using the `.groups` argument.
# A tibble: 0 x 3
# Groups:   Assay [0]
# i 3 variables: Assay <chr>, M <int>, F <int>


I think this particular error occurred because OlinkId was changed by deleting part of the string "OID2" in order to merge olink qced data with available phenotype data. As soon as I restore merged OlinkID to the original one. this error was replaced by another one:

Original Error:

anova_results_oneway <- olink_ttest(df = biomarker_data3,
                                     variable = "Sex")
0 assay(s) exhibited assay QC warning. For more information see the Assay_Warning column.
Error in olink_ttest(df = biomarker_data3, variable = "Sex") : 
  No assays passing initial check. T-test will not be performed.
 View(biomarker_data2)
 biomarker_data2$OlinkID=paste0("OID2",biomarker_data2$OlinkID )
anova_results_oneway <- olink_ttest(df = biomarker_data3,
                                      variable = "Sex")
Error in olink_ttest(df = biomarker_data2, variable = "Sex") : 
  There are 943 samples that do not have a unique level for your variable. Only one level per sample is allowed.

**Comment by karpat90** [comment]
We found the issue with participants IDs and tests work now! Thank you!

**Comment by kathy-nevola** [comment]
Great to hear it!
