### ISSUE TITLE
object 'Panel' not found

### ISSUE THREAD

**Issue by pabloheimplatz** [Olink-Proteomics/OlinkRPackage#87]
Hi,
I got some Link Data from you and tested this repo code on macOS.
But I always got the following error message:
```
Error in filter(., Panel == "Olink CARDIOMETABOLIC") : 
  object 'Panel' not found
```

Regardless if I use RStudio or R via Terminal and regardless if I use the `npx_data1` or my own dataset with a custom filter for my own panel filter.

Maybe you have an idea to this?

**Comment by kathy-nevola** [comment]
Hello!

Can you provide the code that caused the error and the version of Olink Analyze you are using? 

The filter function is from dplyr, so if you are using filter outside of Olink Analyze you will also need to call library(dplyr) to load the filter function. The read_NPX function will convert panel names to be sentence case, so that may be what is causing the error, so the filter call might need to be data %>% filter(Panel == "Olink Cardiometabolic") as well.

Let me know if either of those work or if you have any other questions.

Thanks!

**Comment by kathy-nevola** [comment]
I will close this for now. If there are any additional questions or problems, feel free to reach out to biostattools@olink.com.
